### ISSUE TITLE
SurrealKV limitations

### ISSUE THREAD

**Issue by itsezc** [surrealdb/surrealkv#7]
There is a downstream issue I've raised for Surreal: https://github.com/stalwartlabs/mail-server/issues/23 and several points were brought up in context of the KV backends supported by Surreal, specifically on this comment https://github.com/stalwartlabs/mail-server/issues/23#issuecomment-1837481073. For some additional context, the particular issue in question is related to Stalwart Mail Server, a rust based fullstack mail solution. 

Some points that were brought up were:

> SurrealDB is not able to store anything larger than 100KB in FoundationDB and 8MB in TiKV. And, in the case of FoundationDB, any transaction larger than 10MB will fail. These limitations also apply to full-text indexing, storing more than a hundred thousands documents in SurrealDB will also result in errors once the RoaringTreemaps grow over 100KB.

> SurrealDB website they list both FDB and TiKV as [complete](https://surrealdb.com/features) but based on the developer's response it is clear that their support for distributed environments is far from complete.

How does SurrealKV stack up against alternatives? with the comments from the author of the issue in mind. My goal here is to understand the limitations and work around these, specifically where Stalwarts Surreal storage backend is concerned.

Related:
- https://github.com/surrealdb/surrealdb/pull/37#issuecomment-1837231824

**Comment by arriqaaq** [comment]
Hi @itsezc,

Thank you for the question. SurrealKV is being designed as an in-memory KV store, designed specifically as a backend store for surrealdb. Currently, it functions as a key-value store and can be considered as a storage engine (similar to rocksdb). Our next step involves the development of the distributed SurrealKV store, which is intended to replace fdb and tikv. This effort is aimed at addressing the limitations you've highlighted and those we've encountered in our own experiences. 

As we progress, our initial focus is on getting the storage engine operational. We plan to test it as an embedded store within surrealdb, aiming to resolve issues encountered with rocksdb. Following this, we will shift our focus to building the distributed store.

We are looking to resolve a bunch of the issues the author has mentioned with regards to tikv and fdb. Interestingly, surrealdb is being utilized across various use cases, and given that each database has its own set of limitations, encountering these limitations is an inherent aspect of the process. 

In order to provide a comprehensive comparison of SurrealKV against alternatives, could you please specify the exact features you are interested in comparing? Additionally, could you clarify whether your interest lies in using SurrealKV as an embedded store?

**Comment by CanRau** [comment]
Personally I'm interested in Surreal as embedded db (in NodeJS) and am curious if SurrealKV will only support in-memory, as your comment suggests, so it won't be disk backed, or is this planned for the future?

**Comment by arriqaaq** [comment]
Hey @CanRau,

I believe SurrealKV (skv) could be an excellent fit for your project. Just to clarify, skv is disk-backed, with additional durability support through a write-ahead log (WAL). Currently, I'm in the process of merging all the pull requests to release the first fully functional version of the KV store, and I'm just wrapping up work on the async store.

When we refer to an in-memory or main-memory database, we mean the ability to store the index in-memory while ensuring durability by backing it up on disk. It's more than just an in-memory data structure. If you're looking for something similar, [tart](https://github.com/surrealdb/tart) might be a suitable option.

We plan to publish detailed blogs on these topics in the next few weeks, which should provide further clarity.

**Comment by CanRau** [comment]
😻 That sounds amazing thank you for the detailed reply 🥰

**Comment by arriqaaq** [comment]
@itsezc 

1) While Redis, RocksDB, RedB, SurrealKV, etc., are considered embedded databases, FDB, despite its ability to run on a single node, is primarily used as a distributed database when considering its integration with SurrealDB (SDB). A distributed database may have more restrictions compared to an embedded database, which you've already highlighted in the discussion thread.

2) We plan to develop a distributed version of SurrealKV, which is as a potential alternative to FDB and TiKV. The future limitations of the distributed transaction layer/protocol on top of SurrealKV is something I can't comment on right now.

3) Currently, SurrealKV (SKV) functions as a key-value store with an in-memory index and an append-only log. The necessity for the index to reside in memory (for MVCC) could pose limitations depending on specific use cases. As per design, there are no constraints on key/value size, hard limit on number of KV pairs in a transaction. And since we are testing it internally, I can't comment right now on possible suggestions to improve performance.

4) SKV can also be used as a blob store, a possible upcoming feature involves storing values separately from keys, but it is not high on the feature list atm.
